server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.91.214.5/IotProductDB?zeroDateTimeBehavior=convertToNull
    username: links
    password: Imiany@2017$
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://39.104.166.109/iot_dev?zeroDateTimeBehavior=convertToNull
#    username: iottest
#    password: Links@2018$
#    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatisMapper/*Mapper.xml
  #type-aliases-package: com.ocean.pojo
  configuration:
    map-underscore-to-camel-case: true
